
package ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CTService2Soap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CTService2Soap {


    /**
     * 
     * @param plateType
     * @param plateNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetExaminePhoto1", action = "http://tempuri.org/GetExaminePhoto1")
    @WebResult(name = "GetExaminePhoto1Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetExaminePhoto1", targetNamespace = "http://tempuri.org/", className = "ws.GetExaminePhoto1")
    @ResponseWrapper(localName = "GetExaminePhoto1Response", targetNamespace = "http://tempuri.org/", className = "ws.GetExaminePhoto1Response")
    public String getExaminePhoto1(
        @WebParam(name = "plateType", targetNamespace = "http://tempuri.org/")
        String plateType,
        @WebParam(name = "plateNo", targetNamespace = "http://tempuri.org/")
        String plateNo);

}
