
package xin.fallen.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CTService2", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://10.35.139.118:8084/CTService2.asmx?wsdl")
public class CTService2
    extends Service
{

    private final static URL CTSERVICE2_WSDL_LOCATION;
    private final static WebServiceException CTSERVICE2_EXCEPTION;
    private final static QName CTSERVICE2_QNAME = new QName("http://tempuri.org/", "CTService2");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.35.139.118:8084/CTService2.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CTSERVICE2_WSDL_LOCATION = url;
        CTSERVICE2_EXCEPTION = e;
    }

    public CTService2() {
        super(__getWsdlLocation(), CTSERVICE2_QNAME);
    }

    public CTService2(WebServiceFeature... features) {
        super(__getWsdlLocation(), CTSERVICE2_QNAME, features);
    }

    public CTService2(URL wsdlLocation) {
        super(wsdlLocation, CTSERVICE2_QNAME);
    }

    public CTService2(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CTSERVICE2_QNAME, features);
    }

    public CTService2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CTService2(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CTService2Soap
     */
    @WebEndpoint(name = "CTService2Soap")
    public CTService2Soap getCTService2Soap() {
        return super.getPort(new QName("http://tempuri.org/", "CTService2Soap"), CTService2Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CTService2Soap
     */
    @WebEndpoint(name = "CTService2Soap")
    public CTService2Soap getCTService2Soap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "CTService2Soap"), CTService2Soap.class, features);
    }

    /**
     * 
     * @return
     *     returns CTService2Soap
     */
    @WebEndpoint(name = "CTService2Soap12")
    public CTService2Soap getCTService2Soap12() {
        return super.getPort(new QName("http://tempuri.org/", "CTService2Soap12"), CTService2Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CTService2Soap
     */
    @WebEndpoint(name = "CTService2Soap12")
    public CTService2Soap getCTService2Soap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "CTService2Soap12"), CTService2Soap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CTSERVICE2_EXCEPTION!= null) {
            throw CTSERVICE2_EXCEPTION;
        }
        return CTSERVICE2_WSDL_LOCATION;
    }

}
